### ISSUE TITLE
Add a way to get notifications of updates

### ISSUE THREAD

**Issue by jennydove** [lfph/lfph-landscape#34]
## Reporters would like to know every time a new card is added

As a reporter, I would like to get a notification every time a new card is added, so I can keep up with which states and countries are launching new apps. 

### Requirements

* There is some method to subscribe to the landscape
* The subscription creates a notification every time a new card is added
    * The notification is probably an email
* The notification itself has a link to the new card and (at least) a summary of what was added: name, URL, GitHub repo

**Comment by dahoum** [comment]
People who are comfortable w/ using github can watch the repository—

https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github

<img width="181" alt="Bildschirmfoto 2020-10-04 um 01 28 05" src="https://user-images.githubusercontent.com/23339925/95003560-dc31da80-05e0-11eb-9028-9d754c0f6d1d.png">

**Comment by jennydove** [comment]
Though if he were to do this, he'd get all the comments and things as well, right? There's no way to just get notifications of merges to prod. So I don't think that will work in this use case.

**Comment by dahoum** [comment]
You are right. There is a long thread requesting per branch notification in github.com. I added a note outlining the value this will have for us: https://github.com/integrations/slack/issues/441#issuecomment-705885975
Shall we, in the meantime, explore other options?

**Comment by jennydove** [comment]
I moved this over to https://github.com/cncf/landscapeapp/issues/678 and am hoping it can get picked up. In the meanwhile, if you have any good ideas on how to get another solution out there, let me know. I tried to see if the landscape generates an RSS, but it does not.

**Comment by AndreyKozlov1984** [comment]
Hi, @jennydove , I've developed most of the landscapeapp. 

First, we already do generate an RSS, just for a completely different purpose - I think to get a list of acquisitions.

 The RSS is generated every day by an automatic updater, thus the best option would be just to generate the new RSS for the `landscapeapp.yml` file, and if something changes to it - interested people will be notified. Also I am able to generate a unique RSS feed for every card, this way people would be able to subscribe only to the unique feed for an individual card.

Let me know which changes you want to get, because, for example, number of github stars may change every day and I doubt that is an important change. Thus I am not sure if it worths to subscribe to the changes in the `processed_landscape.yml`

**Comment by jennydove** [comment]
Thanks Andrey - I think for the moment we'll use the current RSS feed as a POC and/or may just send out updates manually. So at least for now no changes necessary. I'll definitely reach out if that doesn't work. Thank you!
